name: customlabs_backend
description: A sample command-line application.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.4

# Add regular dependencies here.
dependencies:
  shelf: ^1.3.0
  dotenv: ^4.2.0
  logging: ^1.0.0
  # path: ^1.8.0
  mysql1: ^0.20.0
  get_it: ^7.6.0
  shelf_router: ^1.1.0
  dart_firebase_admin:
    git:
      url: git@github.com:Amirala7/dart_firebase_admin.git
      ref: main
      path: packages/dart_firebase_admin
  path: ^1.9.1

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
